// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.JPA.grpc.lib;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messagee = 2;</code>
   */
  java.lang.String getMessagee();
  /**
   * <code>string messagee = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageeBytes();
}
