server:
  port: 8080
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test

---
#user_default
user:
  user-id: 0
  userName: default_userName
  userPassword: default_userPassword
  email: default_email@email.cn
  isdel: 0
---
#jpa
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?charactorEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
---
spring:
  redis:
    database: 0
#    host: 127.0.0.1
#    port: 6379
    password: 123456
#    jedis:
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000