// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.changw98.grpcdemo.generate;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.changw98.grpcdemo.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
