spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fuck?charactorEncoding=utf-8&useSSL=false&serverTimeZone=GMT
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


