#Person:
#  id: 001
#  name: 狗蛋
#  sex: 男
#  birth: 2020/3/18
#  maps: {kk: 001,k2: 002}
#  lists:
#    - lll
#    - www
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver



