// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.changw98.grpcdemo.generate;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_changw98_grpcdemo_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_changw98_grpcdemo_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_changw98_grpcdemo_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_changw98_grpcdemo_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\025com.changw98.grpcdemo\"\031" +
      "\n\tMyRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nMyResponse\022" +
      "\017\n\007message\030\001 \001(\t2\\\n\tMyService\022O\n\010SayHell" +
      "o\022 .com.changw98.grpcdemo.MyRequest\032!.co" +
      "m.changw98.grpcdemo.MyResponseB)\n\036com.ch" +
      "angw98.grpcdemo.generateB\005ProtoP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_changw98_grpcdemo_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_changw98_grpcdemo_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_changw98_grpcdemo_MyRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_changw98_grpcdemo_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_changw98_grpcdemo_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_changw98_grpcdemo_MyResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
