server:
  port: 8080
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test

---
#user_default
user:
  user-id: 0
  userName: default_userName
  userPassword: default_userPassword
  email: default_email@email.cn
  isdel: 0
---
#jpa
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?charactorEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
